from typing import List, Dict
from app.models import Job

# Initial mock seed database
MOCK_JOBS: List[dict] = [
    # SECTION 1: Daily Wage & House Construction Work
    {
        "id": "job-const-01",
        "title": "Senior Wall Painter & Primer Helper",
        "category": "construction",
        "category_name": "Construction & Daily Wage",
        "rate": 950.0,
        "rate_type": "Daily",
        "rate_formatted": "₹950 / day",
        "location": "Andheri West, Mumbai",
        "pincode": "400058",
        "distance": "1.2 km away",
        "shift_timings": "8:30 AM - 5:30 PM",
        "employer_name": "Shree Buildcon Projects",
        "employer_rating": 4.8,
        "verified_employer": True,
        "tags": ["Paid Daily", "Same-Day Start", "Tools Provided"],
        "description": "Urgent requirement for 3 painters for residential renovation project. Daily cash payment guaranteed at end of shift.",
        "urgent": True,
        "tools_provided": True,
        "transport_available": False,
        "contact_phone": "+91 98201 54321",
        "applicants_count": 8
    },
    {
        "id": "job-const-02",
        "title": "House Construction Mason & Concrete Worker",
        "category": "construction",
        "category_name": "Construction & Daily Wage",
        "rate": 1100.0,
        "rate_type": "Daily",
        "rate_formatted": "₹1,100 / day",
        "location": "Bandra East, Mumbai",
        "pincode": "400051",
        "distance": "2.5 km away",
        "shift_timings": "8:00 AM - 5:00 PM",
        "employer_name": "Apex Infra Developers",
        "employer_rating": 4.9,
        "verified_employer": True,
        "tags": ["Paid Daily", "Transport Available", "Tools Provided"],
        "description": "Looking for experienced brick layer mason for 4-day site work. Pickup from Bandra station included.",
        "urgent": False,
        "tools_provided": True,
        "transport_available": True,
        "contact_phone": "+91 98112 33445",
        "applicants_count": 14
    },
    {
        "id": "job-const-03",
        "title": "Plumbing Repair Helper & Fitting Assistant",
        "category": "construction",
        "category_name": "Construction & Daily Wage",
        "rate": 800.0,
        "rate_type": "Daily",
        "rate_formatted": "₹800 / day",
        "location": "Powai, Mumbai",
        "pincode": "400076",
        "distance": "0.9 km away",
        "shift_timings": "9:00 AM - 6:00 PM",
        "employer_name": "QuickFix Plumbing Solutions",
        "employer_rating": 4.7,
        "verified_employer": True,
        "tags": ["Same-Day Start", "Paid Daily"],
        "description": "Assist master plumber with pipe fitting and bathroom leak fixes in apartment complex.",
        "urgent": True,
        "tools_provided": True,
        "transport_available": False,
        "contact_phone": "+91 97690 12890",
        "applicants_count": 5
    },
    {
        "id": "job-const-04",
        "title": "Electrician Helper - Wiring & Trenching",
        "category": "construction",
        "category_name": "Construction & Daily Wage",
        "rate": 850.0,
        "rate_type": "Daily",
        "rate_formatted": "₹850 / day",
        "location": "Goregaon East, Mumbai",
        "pincode": "400063",
        "distance": "3.1 km away",
        "shift_timings": "9:00 AM - 5:00 PM",
        "employer_name": "Sai Electricals",
        "employer_rating": 4.6,
        "verified_employer": True,
        "tags": ["Paid Daily", "Tools Provided", "Same-Day Start"],
        "description": "Commercial building wiring project helper. Basic electrical knowledge preferred.",
        "urgent": False,
        "tools_provided": True,
        "transport_available": True,
        "contact_phone": "+91 98920 88776",
        "applicants_count": 11
    },

    # SECTION 2: Student Part-Time & Flexible Shifts
    {
        "id": "job-stud-01",
        "title": "Math & Science Tutor (Class 6-9)",
        "category": "student",
        "category_name": "Student Part-Time",
        "rate": 300.0,
        "rate_type": "Hourly",
        "rate_formatted": "₹300 / hr",
        "location": "Juhu, Mumbai (Near Mithibai College)",
        "pincode": "400049",
        "distance": "400m from Mithibai College",
        "shift_timings": "5:00 PM - 7:30 PM",
        "employer_name": "Bright Minds Home Tutors",
        "employer_rating": 4.9,
        "verified_employer": True,
        "tags": ["Evening Shifts", "Weekend Only", "No Experience Required"],
        "description": "Engineering / B.Sc college students welcome to teach CBSE syllabus to 2 school kids.",
        "urgent": False,
        "contact_phone": "+91 98200 99887",
        "applicants_count": 19
    },
    {
        "id": "job-stud-02",
        "title": "Event Data Entry & Ticket Scanner Associate",
        "category": "student",
        "category_name": "Student Part-Time",
        "rate": 250.0,
        "rate_type": "Hourly",
        "rate_formatted": "₹250 / hr",
        "location": "BKC, Mumbai",
        "pincode": "400051",
        "distance": "1.8 km from NMIMS",
        "shift_timings": "4 Hours/Day (Flexible)",
        "employer_name": "ShowTime Events Ltd.",
        "employer_rating": 4.8,
        "verified_employer": True,
        "tags": ["3-4 Hours/Day", "Weekend Only", "No Experience Required"],
        "description": "Scan entry QR codes and register attendees for tech conference. Meals provided!",
        "urgent": True,
        "contact_phone": "+91 99301 44556",
        "applicants_count": 27
    },
    {
        "id": "job-stud-03",
        "title": "Part-Time Retail Store Assistant",
        "category": "student",
        "category_name": "Student Part-Time",
        "rate": 200.0,
        "rate_type": "Hourly",
        "rate_formatted": "₹200 / hr",
        "location": "Oberoi Mall, Goregaon",
        "pincode": "400063",
        "distance": "1.2 km away",
        "shift_timings": "6:00 PM - 10:00 PM",
        "employer_name": "Trendz Apparels",
        "employer_rating": 4.5,
        "verified_employer": True,
        "tags": ["Evening Shifts", "3-4 Hours/Day"],
        "description": "Assist customers, organize store displays, and manage inventory during evening rush.",
        "urgent": False,
        "contact_phone": "+91 98211 77665",
        "applicants_count": 15
    },
    {
        "id": "job-stud-04",
        "title": "Weekend Delivery Partner (EV Provided)",
        "category": "student",
        "category_name": "Student Part-Time",
        "rate": 350.0,
        "rate_type": "Hourly",
        "rate_formatted": "₹350 / hr",
        "location": "Powai, Mumbai",
        "pincode": "400076",
        "distance": "500m from IIT Bombay",
        "shift_timings": "Flexible 3-6 Hrs (Sat-Sun)",
        "employer_name": "Express Local Logistics",
        "employer_rating": 4.7,
        "verified_employer": True,
        "tags": ["Weekend Only", "3-4 Hours/Day", "No Experience Required"],
        "description": "Deliver local parcel packages on company provided electric scooter. Valid driving license required.",
        "urgent": True,
        "contact_phone": "+91 97022 11334",
        "applicants_count": 32
    },

    # SECTION 3: Catering, Event & Restaurant Staffing
    {
        "id": "job-cat-02",
        "title": "Live Counter Line Cook & Assistant Chef",
        "category": "restaurant",
        "category_name": "Restaurant & Kitchen",
        "rate": 2200.0,
        "rate_type": "Per Event",
        "rate_formatted": "₹2,200 / event",
        "location": "Worli Sea Face, Mumbai",
        "pincode": "400018",
        "distance": "3.5 km away",
        "shift_timings": "4:00 PM - 11:30 PM",
        "employer_name": "Gourmet Hospitality Co.",
        "employer_rating": 4.8,
        "verified_employer": True,
        "tags": ["Paid Daily", "Same-Day Start"],
        "description": "Handle tandoor & live pasta counter at corporate dinner party. Chef apron provided.",
        "urgent": True,
        "uniform_required": "Chef Coat Provided",
        "event_date": "Needed for Friday Evening Shift",
        "contact_phone": "+91 98199 44332",
        "applicants_count": 12
    },
    {
        "id": "job-cat-03",
        "title": "Kitchen Helper & Commercial Dishwasher",
        "category": "restaurant",
        "category_name": "Restaurant & Kitchen",
        "rate": 750.0,
        "rate_type": "Daily",
        "rate_formatted": "₹750 / day",
        "location": "Bandra West, Mumbai",
        "pincode": "400050",
        "distance": "0.7 km away",
        "shift_timings": "11:00 AM - 9:00 PM",
        "employer_name": "Urban Bistro & Cafe",
        "employer_rating": 4.6,
        "verified_employer": True,
        "tags": ["Paid Daily", "Tools Provided"],
        "description": "Assist head chef with vegetable chopping, kitchen sanitation, and dishwashing station.",
        "urgent": False,
        "uniform_required": "Apron & Gloves Provided",
        "contact_phone": "+91 98203 11223",
        "applicants_count": 9
    },
    # Additional Bonus Categories for Amazon Grid Navigation
    {
        "id": "job-dom-01",
        "title": "Deep Home Cleaning & Dusting Specialist",
        "category": "domestic",
        "category_name": "Domestic & House Help",
        "rate": 800.0,
        "rate_type": "Daily",
        "rate_formatted": "₹800 / day",
        "location": "Lokhandwala, Andheri West",
        "pincode": "400053",
        "distance": "1.6 km away",
        "shift_timings": "9:30 AM - 3:30 PM",
        "employer_name": "CleanHomes Services",
        "employer_rating": 4.8,
        "verified_employer": True,
        "tags": ["Tools Provided", "Paid Daily"],
        "description": "One-day festival deep cleaning job for 3BHK flat. All equipment & materials provided.",
        "urgent": True,
        "contact_phone": "+91 98200 44112",
        "applicants_count": 7
    },
    {
        "id": "job-drv-01",
        "title": "Personal Car Driver - 1 Day Outstation Trip",
        "category": "driver",
        "category_name": "Driver & Delivery",
        "rate": 1400.0,
        "rate_type": "Daily",
        "rate_formatted": "₹1,400 / day",
        "location": "Thane West",
        "pincode": "400601",
        "distance": "4.2 km away",
        "shift_timings": "6:00 AM - 8:00 PM",
        "employer_name": "Private Family Hire",
        "employer_rating": 5.0,
        "verified_employer": True,
        "tags": ["Same-Day Start", "Paid Daily"],
        "description": "Drive automatic sedan car to Lonavala and back. Lunch & toll expenses covered.",
        "urgent": True,
        "contact_phone": "+91 99870 55443",
        "applicants_count": 10
    }
]

MOCK_JOBS[:] = [job for job in MOCK_JOBS if job["category"] == "catering"]

# In-memory stores
USER_PROFILES: Dict[str, dict] = {}
SAVED_JOBS: Dict[str, List[str]] = {}  # mobile -> list of job_ids
JOB_APPLICATIONS: List[dict] = []
